#coding-service-prod.yaml

server:
  port: ${CODING_SERVICE_PORT:8085}

spring:

  mongodb:
    uri: ${MONGO_URI}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS}

    producer:
      retries: ${KAFKA_PRODUCER_RETRIES}
      acks: ${KAFKA_PRODUCER_ACKS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: ${KAFKA_CONSUMER_OFFSET}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"

# eureka:
#   client:
#     service-url:
#       defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
#   instance:
#     prefer-ip-address: true
#     instance-id: ${spring.application.name}:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus


  endpoint:
    health:
      show-details: always


